# 稳定性优先配置
# 适用于网络环境不稳定或 API 兼容性问题

[general]
output_dir = "./downloads"
max_pages = 100
batch_size = 1           # 串行处理，避免并发问题
wait_time = 60           # 保持默认等待时间
request_delay = 1000     # 增加请求间延迟
timeout = 30             # 保持默认超时
user_agent = "Mozilla/5.0 (compatible; MarkdownDownloader/1.0)"

[translation]
enabled = true
source_lang = "auto"
target_lang = "zh"
deeplx_api_url = "https://deepl3.fileaiwork.online/"
max_requests_per_second = 0.5    # 降低请求频率
max_text_length = 2000           # 减少单次处理长度
max_paragraphs_per_request = 5   # 减少段落数
